/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseMusic: typeof import('./../components/BaseMusic.vue')['default']
    ImagePlayer: typeof import('./../components/ImagePlayer.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleToast: typeof import('./../components/SimpleToast.vue')['default']
    SwiperContainer: typeof import('./../components/SwiperContainer.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    Tnmp: typeof import('./../components/tnmp.vue')['default']
    VideoPlayer: typeof import('./../components/VideoPlayer.vue')['default']
  }
}
